local M = {}

function M.get()
	return {
		SagaTitle = { fg = C.monokai_cyan, style = { "bold" } },
		SagaBorder = { fg = C.blue, bg = C.none },
		SagaNormal = { bg = O.transparent_background and C.none or C.darkest_green },
		SagaToggle = { fg = C.green },
		SagaCount = { fg = C.light_green },
		SagaBeacon = { bg = U.darken(C.darker_green, 0.8, C.darkest_green) },
		SagaVirtLine = { fg = C.mint },
		SagaSpinner = { fg = C.monokai_violet, style = { "bold" } },
		SagaSpinnerTitle = { fg = C.monokai_violet, style = { "bold" } },
		SagaText = { fg = C.brown },
		SagaSelect = { fg = C.blue, style = { "bold" } },
		SagaSearch = { link = "Search" },
		SagaFinderFname = { fg = C.brown, style = { "bold" } },
		ActionFix = { fg = C.monokai_magenta },
		ActionPreviewTitle = { fg = C.monokai_violet, bg = O.transparent_background and C.none or C.darkest_green },
		CodeActionText = { fg = C.green },
		CodeActionNumber = { fg = C.monokai_magenta },
		SagaImpIcon = { fg = C.monokai_magenta },
		SagaLightBulb = { link = "DiagnosticSignHint" },
		RenameNormal = { fg = C.brown },
		RenameMatch = { link = "Search" },
		DiagnosticText = { fg = C.brown },
		SagaWinbarSep = { fg = C.monokai_yellow },
		SagaDetail = { link = "Comment" },
		SagaFileName = { fg = C.green, style = { "bold" } },
		SagaFolderName = { fg = C.green, style = { "bold" } },
		SagaInCurrent = { fg = C.monokai_orange },

		-- Lspkind icons support
		LspKindClass = { fg = C.yellow },
		LspKindConstant = { fg = C.monokai_orange },
		LspKindConstructor = { fg = C.blue },
		LspKindEnum = { fg = C.yellow },
		LspKindEnumMember = { fg = C.monokai_cyan },
		LspKindEvent = { fg = C.yellow },
		LspKindField = { fg = C.monokai_cyan },
		LspKindFile = { fg = C.monokai_yellow },
		LspKindFunction = { fg = C.blue },
		LspKindInterface = { fg = C.yellow },
		LspKindKey = { fg = C.red },
		LspKindMethod = { fg = C.blue },
		LspKindModule = { fg = C.blue },
		LspKindNamespace = { fg = C.blue },
		LspKindNumber = { fg = C.monokai_orange },
		LspKindOperator = { fg = C.monokai_blue },
		LspKindPackage = { fg = C.blue },
		LspKindProperty = { fg = C.monokai_cyan },
		LspKindStruct = { fg = C.yellow },
		LspKindTypeParameter = { fg = C.blue },
		LspKindVariable = { fg = C.monokai_orange },
		LspKindArray = { fg = C.monokai_orange },
		LspKindBoolean = { fg = C.monokai_orange },
		LspKindNull = { fg = C.yellow },
		LspKindObject = { fg = C.yellow },
		LspKindString = { fg = C.green },
		-- ccls-specific icons.
		LspKindTypeAlias = { fg = C.green },
		LspKindParameter = { fg = C.blue },
		LspKindStaticMethod = { fg = C.monokai_orange },
		-- Microsoft-specific icons.
		LspKindText = { fg = C.green },
		LspKindSnippet = { fg = C.monokai_violet },
		LspKindFolder = { fg = C.blue },
		LspKindUnit = { fg = C.green },
		LspKindValue = { fg = C.monokai_orange },
	}
end

function M.custom_kind()
	return {
		File = { "󰈙 ", "LspKindFile" },
		Module = { " ", "LspKindModule" },
		Namespace = { "󰌗 ", "LspKindNamespace" },
		Package = { "󰏖 ", "LspKindPackage" },
		Class = { "󰌗 ", "LspKindClass" },
		Method = { " ", "LspKindMethod" },
		Property = { "󰆧 ", "LspKindProperty" },
		Field = { " ", "LspKindField" },
		Constructor = { " ", "LspKindConstructor" },
		Enum = { "󰒻", "LspKindEnum" },
		Interface = { " ", "LspKindInterface" },
		Function = { "󰊕 ", "LspKindFunction" },
		Variable = { " ", "LspKindVariable" },
		Constant = { " ", "LspKindConstant" },
		String = { "󰀬 ", "LspKindString" },
		Number = { "󰎠 ", "LspKindNumber" },
		Boolean = { " ", "LspKindBoolean" },
		Array = { "󰅪 ", "LspKindArray" },
		Object = { "󰅩 ", "LspKindObject" },
		Key = { "󰌋 ", "LspKindKey" },
		Null = { " ", "LspKindNull" },
		EnumMember = { " ", "LspKindEnumMember" },
		Struct = { "󰌗 ", "LspKindStruct" },
		Event = { " ", "LspKindEvent" },
		Operator = { "󰆕 ", "LspKindOperator" },
		TypeParameter = { "󰊄 ", "LspKindTypeParameter" },
		TypeAlias = { " ", "LspKindTypeAlias" },
		Parameter = { " ", "LspKindParameter" },
		StaticMethod = { "󰠄 ", "LspKindStaticMethod" },
		Macro = { " ", "LspKindMacro" },
		Text = { "󰉿 ", "LspKindText" },
		Snippet = { " ", "LspKindSnippet" },
		Folder = { " ", "LspKindFolder" },
		Unit = { "󰉻 ", "LspKindUnit" },
		Value = { " ", "LspKindValue" },
	}
end

-- Backwards compatibility
function M.custom_colors()
	local C = require("catppuccin.palettes").get_palette()
	return {
		normal_bg = C.darkest_green,
		title_bg = C.green,
		red = C.red,
		magenta = C.monokai_magenta,
		orange = C.monokai_orange,
		yellow = C.yellow,
		green = C.green,
		cyan = C.monokai_blue,
		blue = C.blue,
		purple = C.monokai_violet,
		white = C.brown,
		black = C.darkest_green,
	}
end

return M
