name: panvimdoc

on:
  push:
    paths:
      - '**.md'

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: ./
        with:
          vimdoc: panvimdoc
          pandoc: doc/panvimdoc.md
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
